### ISSUE TITLE
Build Gradle Failed

### ISSUE THREAD

**Issue by Lakshit-223** [baqx/feelio#4]
Hello sir, every time I try to launch the app, it shows that you are using deprecated gradle tools. I am unable to run the app. I think you are working  on this project since long and meanwhile there are some upgrades in the gradle building.
So, can you please tell me how can I sort this issue?

**Comment by baqx** [comment]
Send a screenshot

**Comment by baqx** [comment]
Whic version of expo and react native are you using

**Comment by Lakshit-223** [comment]
![Screenshot 2024-07-09 235859](https://github.com/baqx/feelio/assets/131598467/1e83247c-b8e7-46fc-8668-2ec0bbcb3f19)
Can you help me sorting out this?

**Comment by Lakshit-223** [comment]
please reply sir.

**Comment by baqx** [comment]
I'll look into it and get back to you

**Comment by baqx** [comment]
Kindly use this commit
[https://github.com/baqx/feelio/tree/b8a9fb432f18075019d6756371569873448f7ce9](https://github.com/baqx/feelio/tree/b8a9fb432f18075019d6756371569873448f7ce9)

**Comment by Lakshit-223** [comment]
what link is it? It is just opening the main page of the repository. Can you please specify what commit is it exactly?

**Comment by baqx** [comment]
It's the link to this commit - b8a9fb4
